global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporters'
    static_configs:
      - targets:
        - pi-hole:9100
        - pi-tor:9100
        - pi-monitor:9100
        - pi-nas:9100
        - pi-k-master:9100
        - pi-k-worker-1:9100
        - pi-k-worker-2:9100
