---
global:
  scrape_interval: 5s  # How often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - pi-hole:9100
          - pi-tor:9100
          - pi-monitor:9100
          - pi-nas:9100
          - pi-k-master:9100
          - pi-k-worker-1:9100
          - pi-k-worker-2:9100
          - pi-runt:9100

  - job_name: 'loki'
    static_configs:
      - targets: ['localhost:3100']
