---
  - import_playbook: playbooks/run-utilities.yml
  - import_playbook: playbooks/setup-monitoring-stack.yml


# - import_playbook: playbooks/host-group/dns/setup-dns-sinkhole.yml
# - import_playbook: playbooks/host-group/tor/setup-tor-wifi.yml

# - import_playbook: playbooks/host-group/nas/setup-nas-drives.yml

# - import_playbook: playbooks/host-group/kubernetes/setup-kubernetes.yml

# - import_playbook: playbooks/host-group/pis/setup-dd-backup.yml
# - import_playbook: playbooks/host-group/pis/setup-restic-backup.yml