---
  - import_playbook: playbooks/utilities/set-ansible-sudo-pwordless.yml
  - import_playbook: playbooks/utilities/disable-wifi.yml
  - import_playbook: playbooks/utilities/update-packages.yml

#  - import_playbook: playbooks/host-group/pis/setup-node-exporter.yml
##### fix Determine correct architecture for Node Exporter


#  - import_playbook: playbooks/host-group/pis/setup-promtail.yml
#  - import_playbook: playbooks/host-group/monitoring/setup-monitoring-stack.yml
##### fix a lot

# - import_playbook: playbooks/host-group/dns/setup-dns-sinkhole.yml
# - import_playbook: playbooks/host-group/tor/setup-tor-wifi.yml

# - import_playbook: playbooks/host-group/nas/setup-nas-drives.yml

# - import_playbook: playbooks/host-group/kubernetes/setup-kubernetes.yml

# - import_playbook: playbooks/host-group/pis/setup-dd-backup.yml
# - import_playbook: playbooks/host-group/pis/setup-restic-backup.yml