---
  - import_playbook: playbooks/host-group/router/restore-router-from-backup.yml
  - import_playbook: playbooks/run-utilities.yml
  - import_playbook: playbooks/host-group/nas/setup-nas.yml
  
# - import_playbook: playbooks/host-group/kubernetes/setup-kubernetes-cluster.yml
# - import_playbook: playbooks/setup-monitoring-stack.yml # amend to be compatible with kubernetes targets and storing of data to nas

# - import_playbook: playbooks/host-group/dns/setup-dns-sinkhole.yml
# - import_playbook: playbooks/host-group/tor/setup-tor-wifi.ym

# - import_playbook: playbooks/host-group/pis/setup-restic-backup.yml # back up of NAS data