---
- name: Backup OpenWRT router config
  hosts: router
  gather_facts: false
  become: false
  vars:
    remote_backup_path: "/tmp/openwrt-backup.tar.gz"
    local_backup_path: "playbooks/host-group/router/backups/openwrt-backup.tar.gz"

  tasks:
    - name: Generate OpenWRT backup archive on router
      raw: sysupgrade -b {{ remote_backup_path }}
      changed_when: false

    - name: Copy backup from router using scp (controller-side)
      delegate_to: localhost
      ansible.builtin.command: >
        scp -i ~/.ssh/ansible -o StrictHostKeyChecking=no root@{{ inventory_hostname }}:{{ remote_backup_path }} {{ local_backup_path }}
      register: scp_result
      changed_when: false
      failed_when: scp_result.rc != 0

    - name: Delete backup file from router
      raw: rm -f {{ remote_backup_path }}
      changed_when: false
