---
- name: Set up passwordless sudo for ansible user
  hosts: pis
  become: true
  tasks:
    - name: Ensure ansible user has passwordless sudo
      lineinfile:
        path: /etc/sudoers.d/ansible
        line: "ansible ALL=(ALL) NOPASSWD:ALL"
        create: yes
        mode: '0440'
        validate: 'visudo -cf %s'
