- name: Disable WiFi on all Raspberry Pis
  hosts: pis:!pi-tor
  become: true
  tasks:
    - name: Ensure WiFi is disabled in /boot/firmware/config.txt
      lineinfile:
        path: /boot/firmware/config.txt
        line: "dtoverlay=disable-wifi"
        state: present
      register: config_wifi

    - name: Ensure WiFi modules are blacklisted
      lineinfile:
        path: /etc/modprobe.d/raspi-blacklist.conf
        line: "{{ item }}"
        create: yes
        state: present
      loop:
        - "blacklist brcmfmac"
        - "blacklist brcmutil"
      register: blacklist_result

    - name: Reboot to enable configuration
      reboot:
        msg: "Rebooting to apply WiFi disablement"
        connect_timeout: 5
        reboot_timeout: 300
      register: reboot_status
      changed_when: config_wifi.changed or blacklist_result.changed
