---
- name: Install Node Exporter on all Raspberry Pis
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
          - tar
        state: present
        update_cache: yes

    - name: Get the latest Node Exporter release version
      uri:
        url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
        method: GET
        return_content: yes
      register: github_release

    - name: Extract version tag from JSON response
      set_fact:
        node_exporter_version: "{{ github_release.json.tag_name | regex_replace('^v', '') }}"

    - name: Determine correct architecture for Node Exporter
      set_fact:
        node_exporter_arch: "{% if 'pi-runt' in inventory_hostname %}armv6{% else %}armv7{% endif %}"

    - name: Check if Node Exporter is already installed
      command: "/usr/local/bin/node_exporter --version"
      register: installed_version_output
      ignore_errors: yes
      changed_when: false

    - name: Extract installed version (if available)
      set_fact:
        installed_version: "{{ installed_version_output.stdout_lines[0] | regex_search('node_exporter, version ([^ ]+)', '\\1') | first }}"
      when: installed_version_output.stdout_lines is defined
      ignore_errors: yes

    - name: Compare installed version with latest
      set_fact:
        needs_update: "{{ installed_version is not defined or installed_version != node_exporter_version }}"

    - name: Download and install Node Exporter if outdated or missing
      shell: |
        cd /tmp
        curl -LO https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz
        tar -xzf node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz
        mv node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter /usr/local/bin/
      args:
        creates: /usr/local/bin/node_exporter
      when: needs_update

    - name: Deploy `node_exporter.service` only if different
      copy:
        src: playbooks/monitoring/files/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: '0644'
      notify: Restart Node Exporter

    - name: Enable and start Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started

  handlers:
    - name: Restart Node Exporter
      systemd:
        name: node_exporter
        state: restarted
